### ISSUE TITLE
Jagged icons

### ISSUE THREAD

**Issue by Perelandra0x309** [HaikuArchives/SuperPrefs#6]
The icons look jagged compared to if you look at the preflets in a Tracker window.  Could be several things, maybe try using B_RGBA32 instead of B_CMAP8 for the bitmap.  Or you may get a better result by using BIconUtils::GetVectorIcon or BNodeInfo::GetTrackerIcon

**Comment by anirudhmurali** [comment]
Now using B_RGBA32. I don't see much difference between those two. What was the issue with B_CMAP8? Were you talking about the icons being slightly pixelated?

**Comment by Perelandra0x309** [comment]
Yes, pixelated, the colors were off and the shadows were missing.
